<?php

namespace App\Livewire\Admin;

use Livewire\Component;
use Livewire\WithPagination;
use App\Models\LeaveRequest;
use App\Models\User;
use App\Notifications\LeaveRequestApproved;

class LeaveTable extends Component
{
    use WithPagination;

    public $statusUpdates = [];

    public function updateStatus($leaveId, $status)
    {
        $leaveRequest = LeaveRequest::find($leaveId);
        if ($leaveRequest) {
            $leaveRequest->status = $status;
            $leaveRequest->save();

            // ✅ Send notification to the ticket owner
            $leaveRequest->user->notify(new LeaveRequestApproved($leaveRequest));
            // ✅ Livewire browser event for feedback
            $this->dispatch('swal:success', message: 'Ticket status updated successfully.');
        } else {
            $this->dispatch('swal:error', message: 'Ticket not found.');
        }
    }   



    public function render()
    {
        // Get tickets generated by users under this admin
        $userIds = User::where('parent_id', auth()->id())->pluck('id');

        $leaves = LeaveRequest::with(['user'])
            ->whereIn('user_id', $userIds)
            ->orderBy('created_at', 'desc')
            ->paginate(10);

        return view('livewire.admin.leave-table', [
            'leaves' => $leaves,
        ]);
    }
}
